### PR TITLE
Fix 402

### LINKED ISSUE #402: Init: Issue when creating buckets
# Overview

We have an issue on to tag buckets on east-1 aws region. 

```bash 
LOG: 2022/09/14 20:54:46.923253 /Users/jared/git/kubefirst/github/kubefirst/internal/aws/aws.go:113: [DEBUG] S3 put bucket versioning: &s3.PutBucketVersioningInput{Bucket:(*string)(0x14000828690), VersioningConfiguration:(*types.VersioningConfiguration)(0x140007925d0), ChecksumAlgorithm:"", ContentMD5:(*string)(nil), ExpectedBucketOwner:(*string)(nil), MFA:(*string)(nil), noSmithyDocumentSerde:document.NoSerde{}}
LOG: 2022/09/14 20:54:47.322916 /Users/jared/git/kubefirst/github/kubefirst/internal/aws/aws.go:507: tagging bucket... k1-gitlab-backup-example:kubernickels
LOG: 2022/09/14 20:54:47.323016 /Users/jared/git/kubefirst/github/kubefirst/internal/aws/aws.go:536: operation error S3: PutBucketTagging, failed to resolve service endpoint, an AWS region is required, but was not found
LOG: 2022/09/14 20:54:47.341939 /Users/jared/git/kubefirst/github/kubefirst/internal/aws/aws.go:128: bucket k1-gitlab-backup-example exists
LOG: 2022/09/14 20:54:47.342044 /Users/jared/git/kubefirst/github/kubefirst/internal/aws/aws.go:81: creating chartmuseum bucket k1-chartmuseum-example
LOG: 2022/09/14 20:54:47.342056 /Users/jared/git/kubefirst/github/kubefirst/internal/aws/aws.go:84: region is  us-west-1
LOG: 2022/09/14 20:54:48.222853 /Users/jared/git/kubefirst/github/kubefirst/internal/aws/aws.go:113: [DEBUG] S3 put bucket versioning: &s3.PutBucketVersioningInput{Bucket:(*string)(0x14000829ab0), VersioningConfiguration:(*types.VersioningConfiguration)(0x1400052e6f0), ChecksumAlgorithm:"", ContentMD5:(*string)(nil), ExpectedBucketOwner:(*string)(nil), MFA:(*string)(nil), noSmithyDocumentSerde:document.NoSerde{}}
LOG: 2022/09/14 20:54:48.507543 /Users/jared/git/kubefirst/github/kubefirst/internal/aws/aws.go:507: tagging bucket... k1-chartmuseum-example:kubernickels
LOG: 2022/09/14 20:54:48.507689 /Users/jared/git/kubefirst/github/kubefirst/internal/aws/aws.go:536: operation error S3: PutBucketTagging, failed to resolve service endpoint, an AWS region is required, but was not found
LOG: 2022/09/14 20:54:48.527312 /Users/jared/git/kubefirst/github/kubefirst/internal/aws/aws.go:128: bucket k1-chartmuseum-example exists
LOG: 2022/09/14 20:54:49.528587 /Users/jared/git/kubefirst/github/kubefirst/cmd/init.go:172: BucketRand() complete
```

### PR DESCRIPTION
**Pull request by converge**
fix #402 

the issue was:
- we have a technical debt to improve how we connect to AWS that is documented in the `aws/aws.go` file. today, every time we want to connect to some AWS resource, we instantiate a new connection, in one of these instantiation the connection was funky. updating the single AWS call to use the regular way to connect fixed the issue.

tested for the following regions:

`eu-central-1, us-east-1 and us-west-1`

### CODE REVIEW

File: internal/progressPrinter/progress.go [hunk 1]
```diff
@@ -103,7 +103,6 @@ func LogMessage(message string) {
 //
 // no need to instanciate, it is a singleton, only one instance already started before use.
 func AddTracker(key string, title string, total int64) string {
```
Comment (6za) [inline internal/progressPrinter/progress.go:105]: Is this a change related to the issue? This sleeps is to give animation effect on the start of new bars?

**Review by 6za — APPROVED** [review]
Does it fix the issue? I was not able to understand the  real change. @marinhojess this may impact your code you touched. You may want pull this code once merged.

File: internal/progressPrinter/progress.go (hunk 1 above)
Comment (converge) [reply internal/progressPrinter/progress.go:105]: I never saw the animation to be honest. I would like to have it as quick as possible in the screen to speed up the job.

if you want to keep it, can we decrease the waiting time by half?

**Comment by converge** [comment]
> Does it fix the issue? I was not able to understand the real change. @marinhojess this may impact your code you touched. You may want pull this code once merged.

it's basically before the AWS connection was funky, no idea how that was working until now, the `s3.New()` tries to use a previous opened connection, and `NewAws()` instantiate a new connection passing the required arguments, region, etc.
