### PR TITLE
Fix 1038

### LINKED ISSUE #1038: [WSL][Localhost] Error when pressing ENTER in localhost installation
### **Description**

Error when trying to open github page at the beginning of localhost installation.

### **Environment**

**kubefirst-cli golang utility version**: development
**operating system**: Linux - Ubuntu (WSL)

### **Screenshots**

image

### Steps to reproduce

Run `go run . local`

### Expected behaviour

Press Enter and open github page on browser.

### PR DESCRIPTION
**Pull request by converge**
this PR:
- enable Linux machines to open GH login token issue step
- uses non blocker call to open user browser

closes #1038

### CODE REVIEW

File: internal/handlers/github.go [hunk 1]
```diff
@@ -90,7 +89,8 @@ func (handler GitHubHandler) AuthenticateUser() (string, error) {
 		return "", err
 	}
 
-	if err = exec.Command("open", "https://github.com/login/device").Start(); err != nil {
+	if err = pkg.OpenBrowser("https://github.com/login/device"); err != nil {
+		log.Error().Msgf("error opening browser: %s", err)
 		return "", err
```
Comment (6za) [inline internal/handlers/github.go:94]: Will this error fail the installer?

Comment (6za) [reply internal/handlers/github.go:94]: For containers run, there is not "browser".. so it would prevent container runs or machine without X if this breaks the installer, if not a error that would fail the installer. I see no issues with it.

Comment (converge) [reply internal/handlers/github.go:94]: the github device validation needs a browser to issue a token, containers users needs to pass the token via configuration

Comment (6za) [reply internal/handlers/github.go:94]: the point is that if tis fails, I can test device token from container. I can access the link, but I can't open the browser. 

If this break the install the missing browser, we should avoid. As it would work, I used before without token. We are failing for no good reason the installer.

Comment (converge) [reply internal/handlers/github.go:94]: I actually didnt add this into this PR, I just added the log.

let's move this discussion into a different topic since it's not the PR goal https://github.com/kubefirst/kubefirst/discussions/1076

**Review by 6za — APPROVED** [review]
