### PR TITLE
Fix atlantis GitHub webhook

### LINKED ISSUE #398: 1.9.x - ensure atlantis is wired properly on github installs
# Overview 

Based on tests, it seems atlantis is not properly wired into github installs. 

The goal of this task is to ensure feature parity between gitlab/github installs, meaning that atlantis works as in gitlab inside a github installation. 

Places of interest top review:
https://github.com/kubefirst/gitops-template/blob/main/terraform/vault/bootstrap/secrets.tf#L4
> secrets loaded into atlantis 

https://www.runatlantis.io/docs/server-configuration.html
> Atlantis configs

https://github.com/kubefirst/gitops-template/blob/main/components/atlantis/application.yaml#L22
> Atlantis helm values, initial setup properties.

### PR DESCRIPTION
**Pull request by pagottoo**
Closes #398 

With this PR we create a webhook configuration in the gitops repo, set a passcode, and inform the terraform vault modules to be used on Atlantis configuration.

### CODE REVIEW

**Review by 6za — APPROVED** [review]
lgtm

File: pkg/helpers.go [hunk 1]
```diff
@@ -25,6 +27,8 @@ type RegistryAddon struct {
 	} `yaml:"metadata"`
 }
 
+var letters = []rune("abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ")
```
Comment (converge) [inline pkg/helpers.go:30]: is `letters` only used in `randSeq()` function?

maybe it's a good idea to include it in the function scope like:
```go
func randSeq( ... ) ... {
  var letter = []rune( ... )
  runeSlice := make ...
  ...
}
```

in this way we avoid having global scope variable.

**Review by converge — DISMISSED** [review]
added a comment, feel free to use it or not

**Review by 6za — APPROVED** [review]
